using N19_HT2;

var aggregation = new Aggregation();
var array  = new int[]{1, 2, 10, 9, 3, 4, 8, 7, 5, 6};
Console.WriteLine($"Sum: {aggregation.Sum(array)}");
Console.WriteLine($"Average: {aggregation.Average(array)}");
Console.WriteLine($"Max: {aggregation.Max(array)}");
Console.WriteLine($"Min: {aggregation.Min(array)}");
var int1 = 6;
var int2 = int.MaxValue;
var int3 = -10;
var int4 = int.MinValue;
Console.WriteLine($"\nBefore increament method: {int1}");
aggregation.Increament(ref int1);
Console.WriteLine($"After increament method: {int1}\nBefore decreament method: {int1}");
aggregation.Decreament(ref int1);
Console.WriteLine($"Afetr decreament method {int1}");
Console.WriteLine($"\nBefore increament method: {int2}");
aggregation.Increament(ref int2);
Console.WriteLine($"After increament method: {int2}\nBefore decreament method: {int2}");
aggregation.Decreament(ref int2);
Console.WriteLine($"Afetr decreament method {int2}");
Console.WriteLine($"\nBefore increament method: {int3}");
aggregation.Increament(ref int3);
Console.WriteLine($"After increament method: {int3}\nBefore decreament method: {int3}");
aggregation.Decreament(ref int3);
Console.WriteLine($"Afetr decreament method {int3}");
Console.WriteLine($"\nBefore increament method: {int4}");
aggregation.Increament(ref int4);
Console.WriteLine($"After increament method: {int4}\nBefore decreament method: {int4}");
aggregation.Decreament(ref int4);
Console.WriteLine($"Afetr decreament method {int4}");