using N20_HT1;

var provider = new UzumPaymentProvider();
var onlineMarket = new OnlineMarket(provider);
var destinationCard = new KapitalUzcard("Qandaydir bank");
onlineMarket.destinationCard = destinationCard;
var product1 = new Product("Non", 3500);
var product2 = new Product("Yog'", 25000);
var product3 = new Product("Choy", 5000);
var product4 = new Product("Un", 50000);
onlineMarket.Add(product1);
onlineMarket.Add(product2);
onlineMarket.Add(product3);
onlineMarket.Add(product4);
onlineMarket.ShowProducts();
var card = new MilliyHumo("yana qanaqadir bank");
card.Balance = 200_000;
Console.Write("Nima sotib olasiz?\nNomini kiriting: ");
var nameOfProduct = Console.ReadLine();
Console.Write("Nechta olasiz: ");
var number = Convert.ToInt32(Console.ReadLine());
onlineMarket.Buy(nameOfProduct, number, card);
Console.Write("Nima sotib olasiz?\nNomini kiriting: ");
nameOfProduct = Console.ReadLine();
Console.Write("Nechta olasiz: ");
number = Convert.ToInt32(Console.ReadLine());
onlineMarket.Buy(nameOfProduct, number, card);
Console.Write("Nima sotib olasiz?\nNomini kiriting: ");
nameOfProduct = Console.ReadLine();
Console.Write("Nechta olasiz: ");
number = Convert.ToInt32(Console.ReadLine());
onlineMarket.Buy(nameOfProduct, number, card);
Console.Write("Nima sotib olasiz?\nNomini kiriting: ");
nameOfProduct = Console.ReadLine();
Console.Write("Nechta olasiz: ");
number = Convert.ToInt32(Console.ReadLine());
onlineMarket.Buy(nameOfProduct, number, card);
Console.WriteLine($"Kartada qolgan pul: {card.Balance}");
Console.WriteLine(onlineMarket.destinationCard.Balance);